# Training Hyper-parameters which are not required when doing inference
TrainingSetting:
  
  # General training settings
  random_seed: 123 # Random seed for initializing model parameters which help reproduce experiments
  max_to_keep: 10 # Maximum number of lastest checkpoints to save
  sample_rate: 16000 # Sampling rate for audio-related summaries
  fps: 25 # FPS for video-related summaries
  scalar_summary_step: 1000 # Saving intervals for scalar-kind summaries, e.g. losses
  save_every_step: 1000 # Saving intervals for models
  maximum_train_steps: 50000 # Maximum training steps
  maximum_train_epochs: 1000 # Maximum training epochs
  
  # LiGS training settings
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30_000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.005
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 25_000
  densify_grad_threshold: 0.0002
  oneupSHdegree_every_steps: 1000
  
  # Gaussian Splatting densify/clone/split settings
  clone_options:
    start_step: 0
    stop_step:
  split_options:
    start_step: 0
    stop_step:
    N: 2
    scale_factor: 1
  prune_options:
    start_step: 0
    stop_step:
    prune_bbox:
      enabled: True
      scale: 1.1
    prune_scaling:
      enabled: False
      prob_accum_sum: 0.9999
    prune_outlier:
      enabled: False
      n_neighbours: 10
      std: 0.05
    prune_edge:
      enabled: False
      max_scaling: 0.1
    prune_alpha:
      enabled: False
    prune_spike:
      enabled: False
      ratio: 0.00001
  merge_options:
    start_step: 0
    stop_step:

  # Loss settings
  loss:
    # General loss settings for LiGS
    masking:
      mask_pred: False # Masking predicted images with alpha before loss calculation
      mask_input: True # Masking real images with current background(may be sampled randomly) before loss calculation
      exclude_mask_loss: False # Excluding loss computation for masked area or not
      random_bg: True # Setting background randomly to avoid spikes around the boundaries between foreground and background
    regularizer:
      opacity: # Regularizer for enforcing opacities to be close to 1
        enabled: False
        scale: 1
      frequency:
        enabled: False
        T0: 500
        T: 25000
        D0: 5
        wl: 0.0001
        wh: 0.0001
        h_reverse: False
    vgg19: # VGG
      enabled: False
      vgg_path: resources/models/vgg19-dcbb9e9d.pth
      vgg_ms: True # Mean-Variance correction
      vgg_layer_idx: [2, 7, 12, 21, 30] # VGG feature map indexes
      vgg_ws: [0.03125, 0.0625, 0.125, 0.25, 0.5] # Weights for VGG feature maps, MUST has the same size with vgg_layer_idx
    # Loss settings for Relightable Gaussians
    religtable_gaussian:
      scale_pbr: 1
      scale_depth: 1
      scale_normal_mvs_depth: 0.01
      scale_normal_render_depth: 0.01
      scale_light: 0.01
      scale_base_color: 0.005
      scale_base_color_smooth: 0.006
      scale_metallic_smooth: 0.002
      scale_roughness_smooth: 0.002
      scale_mask_entropy: 0
    # Loss settings for Gaussian Shaders
    gaussian_shader:
      lambda_zero_one: 0.001
      lambda_predicted_normal: 0.2
      lambda_delta_reg: 0.001
    guiding:
      normal:
        enabled: False
        scale: 0.00016
      depth:
        enabled: False
        scale: 0.00016

  # Debug settings
  debug:
    vis_grad: False
    vis_diff: True
    vis_vgg: False

# Inference dataset settings
InferDatasetSetting:
  camera_upsample_factor: 5
  render_fps: 25
  fixed_fidx: 80

# Testing dataset settings, for evaluating models's performance, including paired and unpaired data generations
TestDatasetSetting:
  lookat_position: [0, 0, 0] # Camera lookat location for unpaired data generation
  fx: null # Use focal x in dataset by default
  fy: null # Use focal y in dataset by default
  fs: 0 # focal change step
  fr: 0 # focal change rate
  width: null # image width, set by dataset
  height: null # image height, set by dataset
  xmax: 8 # Maximum distance between camera and object along X-axis
  ymax: 6 # Maximum distance between camera and object along Y-axis
  zspan: [0, 5] # Height range of camera in global coordinate
  n_xy: 200 # Samples in XY-plane
  n_z: 10 # Samples in height

# Training dataset settings, mainly used in data preparation stage
TrainDatasetSetting:
  load_down_scale: 1 # downsampling ratio: 1, 2, 4, 8
  alpha_threshold: 240 # Alpha threshold for changing alpha into {0,1}
  multi_down_scales: [1.0]
  preload: True
  feature_settings:
    image: 
      dir: images
      suffix: .jpg
    alpha:
      dir: masks/sam
      suffix: .npy
    depth: null
    normal: null
    albedo: null
  run_diagnosis: True # Saving diagnosis videos in each stage
  # parameters for segmentation
  segmentation_prompt: "car mask" # Prompts for extracting segmentations
  # parameters for pcd_clean
  pcd_clean_pixel_border: 5
  check_bbox_valid_length: 20
  check_bbox_valid_border: 20
  check_bbox_valid_bbox_diff: 50
  alpha_border: 1
  # parameters for pcd_standard
  pcd_standard_epsilon: 1
  pcd_standard_loop_count: 1
  pcd_standard_interval: 0.1 
  pcd_standard_interval_decay_rate: 0.5 
  pcd_standard_degree_decay_rate: 0.5
  # parameter for rescaling point cloud manually
  rescales: [1.3, 1.3, 1.3]
  novel_view:
    enabled: False
    mesh_subdir: meshs/rasted_1/points3D.ply
    rate: 0.5
    scale: 1
    X: [3, 8] # X-axis range [min, max]
    Y: [3, 5] # Y-axis range [min, max]
    Z: [0, 5] # Z-axis range [min, max]

# Model settings, most of them may be used in other platforms, e.g. SIBR
ModelSetting:
  network_class: LiGaussianModel # Network class name
  generator_class: GaussianGenerator # Generator class name
  sh_degree: 1
  max_points: 100000 # Maximum number of gaussians
  init_pcd_interval: 1 # Interval for reading points from ply file in order to downsample when there are too many points in ply
  white_background: False # Setting background for rendering

  # These are placeholders, the parameters are set when training the model, DO NOT modify here
  dataset_dir: null # dataset dir set by datasets





